spring:
  datasource:
    #请配置自己的数据库信息
    username: root
    password: 888888
    url: jdbc:mysql://localhost/springboot2?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties: {hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect}
  thymeleaf:
    cache: false
  redis:
    #此处配置Redis服务器IP地址，需自己手动配置
    host: 192.168.127.133

